name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Google Analytics ID in _config.yml
        run: |
          echo "google_analytics: '${{ secrets.GOOGLE_ANALYTICS_ID }}'" >> _config.yml

      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./_site
