name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variables (for debugging)
        run: printenv

      - name: Replace Google Analytics ID
        run: |
          GA_ID=${{ secrets.GOOGLE_ANALYTICS_ID }}
          echo "Google Analytics ID: $GA_ID"
          sed -i "s/GOOGLE_ANALYTICS_ID_PLACEHOLDER/$GA_ID/g" index.html
          cat index.html

      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./_site
