name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace Google Analytics ID
        run: |
          GA_ID=${{ secrets.GOOGLE_ANALYTICS_ID }}
          sed "s/mykey/$GA_ID/g" index.html > temp_index.html
          mv temp_index.html index.html[_{{{CITATION{{{_2{GitHub - actions/deploy-pages: GitHub Action to publish artifacts to ...](https://github.com/actions/deploy-pages)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./
