name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display contents of index.html before replacement
        run: cat index.html

      - name: Replace Google Analytics ID
        run: sed -i "s/mykey/${{ secrets.GOOGLE_ANALYTICS_ID }}/" index.html

      - name: Display contents of index.html after replacement
        run: cat index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
