name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace Google Analytics ID
        run: |
          GA_ID=${{ secrets.GOOGLE_ANALYTICS_ID }}
          echo "Replacing mykey with: $GA_ID"
          sed "s/mykey/$GA_ID/g" index.html > temp_index.html
          mv temp_index.html index.html

      - name: Display contents of index.html after replacement
        run: cat index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./
